/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWebappProductsRouteImport } from './routes/api/webapp/products'
import { Route as ApiWebappOrderRouteImport } from './routes/api/webapp/order'
import { Route as ApiWebappCheckRouteImport } from './routes/api/webapp/check'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicTelegramWatchdogRouteImport } from './routes/api/public/telegram/watchdog'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebappProductsRoute = ApiWebappProductsRouteImport.update({
  id: '/api/webapp/products',
  path: '/api/webapp/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebappOrderRoute = ApiWebappOrderRouteImport.update({
  id: '/api/webapp/order',
  path: '/api/webapp/order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebappCheckRoute = ApiWebappCheckRouteImport.update({
  id: '/api/webapp/check',
  path: '/api/webapp/check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramWatchdogRoute =
  ApiPublicTelegramWatchdogRouteImport.update({
    id: '/api/public/telegram/watchdog',
    path: '/api/public/telegram/watchdog',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/webapp/check': typeof ApiWebappCheckRoute
  '/api/webapp/order': typeof ApiWebappOrderRoute
  '/api/webapp/products': typeof ApiWebappProductsRoute
  '/api/public/telegram/watchdog': typeof ApiPublicTelegramWatchdogRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/webapp/check': typeof ApiWebappCheckRoute
  '/api/webapp/order': typeof ApiWebappOrderRoute
  '/api/webapp/products': typeof ApiWebappProductsRoute
  '/api/public/telegram/watchdog': typeof ApiPublicTelegramWatchdogRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/webapp/check': typeof ApiWebappCheckRoute
  '/api/webapp/order': typeof ApiWebappOrderRoute
  '/api/webapp/products': typeof ApiWebappProductsRoute
  '/api/public/telegram/watchdog': typeof ApiPublicTelegramWatchdogRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/webapp/check'
    | '/api/webapp/order'
    | '/api/webapp/products'
    | '/api/public/telegram/watchdog'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/webapp/check'
    | '/api/webapp/order'
    | '/api/webapp/products'
    | '/api/public/telegram/watchdog'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/api/webapp/check'
    | '/api/webapp/order'
    | '/api/webapp/products'
    | '/api/public/telegram/watchdog'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiWebappCheckRoute: typeof ApiWebappCheckRoute
  ApiWebappOrderRoute: typeof ApiWebappOrderRoute
  ApiWebappProductsRoute: typeof ApiWebappProductsRoute
  ApiPublicTelegramWatchdogRoute: typeof ApiPublicTelegramWatchdogRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webapp/products': {
      id: '/api/webapp/products'
      path: '/api/webapp/products'
      fullPath: '/api/webapp/products'
      preLoaderRoute: typeof ApiWebappProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webapp/order': {
      id: '/api/webapp/order'
      path: '/api/webapp/order'
      fullPath: '/api/webapp/order'
      preLoaderRoute: typeof ApiWebappOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webapp/check': {
      id: '/api/webapp/check'
      path: '/api/webapp/check'
      fullPath: '/api/webapp/check'
      preLoaderRoute: typeof ApiWebappCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/watchdog': {
      id: '/api/public/telegram/watchdog'
      path: '/api/public/telegram/watchdog'
      fullPath: '/api/public/telegram/watchdog'
      preLoaderRoute: typeof ApiPublicTelegramWatchdogRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiWebappCheckRoute: ApiWebappCheckRoute,
  ApiWebappOrderRoute: ApiWebappOrderRoute,
  ApiWebappProductsRoute: ApiWebappProductsRoute,
  ApiPublicTelegramWatchdogRoute: ApiPublicTelegramWatchdogRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
